apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: from-ontapnas-snap-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ontapnas
  resources:
    requests:
      storage: 20Mi
  dataSource:
    name: ontapnas-snap-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io